import 'unit_model.dart';

/// المنهج الكامل لأرقامي — 52 وحدة متدرجة من تأسيس مفهوم العدد إلى أساسيات الجبر.
///
/// كل وحدة تسير تربوياً وفق المسار:
/// تعلم → مثال → تفاعل/تدريب → Quiz → نتيجة/تقدم.
///
/// هذه الطبقة تحتوي على المحتوى فقط. منطق فتح الوحدات وتسجيل النتائج يبقى في
/// ProgressTracker ومحرك الأنشطة حتى لا نخلط المحتوى بواجهة المستخدم.
class UnitsData {
  static const int totalUnits = 52;

  static LessonActivityConfig _learn(String title, String explanation, [List<String> examples = const []]) =>
      LessonActivityConfig(titleAr: title, explanationAr: explanation, examplesAr: examples);

  static MultipleChoiceActivityConfig _quiz(List<ChoiceQuestion> questions) =>
      MultipleChoiceActivityConfig(questions);

  static AssessmentActivityConfig _assessment(int n, List<ChoiceQuestion> questions) =>
      AssessmentActivityConfig(titleAr: 'اختبار الوحدة $n', questions: questions);

  static ChoiceQuestion _q(String question, List<String> options, int correct, [String? hint]) =>
      ChoiceQuestion(questionAr: question, options: options, correctIndex: correct, hintAr: hint);

  static UnitModel _unit({
    required int n,
    required String title,
    required String age,
    required String description,
    required String learnTitle,
    required String explanation,
    List<String> examples = const [],
    List<ActivityConfig> extra = const [],
    required List<ChoiceQuestion> quiz,
    List<ChoiceQuestion>? assessment,
  }) {
    return UnitModel(
      id: 'unit_${n.toString().padLeft(2, '0')}',
      order: n,
      titleAr: title,
      ageRangeAr: age,
      descriptionAr: description,
      activities: [
        _learn(learnTitle, explanation, examples),
        ...extra,
        _quiz(quiz),
        _assessment(n, assessment ?? quiz),
      ],
    );
  }

  static final List<UnitModel> units = [
    // ================================================================
    // المرحلة 1 — تأسيس الأعداد 0–5 | 3–4 سنوات
    // ================================================================
    _unit(n: 1, title: 'الرقم 0', age: '3–4 سنوات', description: 'التعرف على 0 وفهم معنى لا شيء.', learnTitle: 'ما معنى 0؟', explanation: 'الصفر يعني أنه لا يوجد أي شيء في المجموعة.', examples: ['0 تفاحات', '0 ألعاب'], extra: [const TraceActivityConfig(0), const DragCountActivityConfig(0)], quiz: [_q('ماذا يعني 0؟', ['لا شيء', 'شيء واحد', 'شيئان'], 0), _q('ما الرقم الذي يمثل عدم وجود أشياء؟', ['1', '0', '2'], 1)]),
    _unit(n: 2, title: 'الرقم 1', age: '3–4 سنوات', description: 'التعرف على 1 وربطه بكمية واحدة.', learnTitle: 'نتعرف على 1', explanation: 'الرقم 1 يمثل شيئاً واحداً.', examples: ['1 كرة', '1 قلم'], extra: [const TraceActivityConfig(1), const DragCountActivityConfig(1), const MatchingActivityConfig([MatchPairSpec(id: '1', leftType: MatchContentType.number, leftValue: 1, rightType: MatchContentType.quantity, rightValue: 1)])], quiz: [_q('كم شيئاً تمثل 1؟', ['0', '1', '2'], 1), _q('ما الرقم الذي يمثل شيئاً واحداً؟', ['1', '2', '0'], 0)]),
    _unit(n: 3, title: 'الرقم 2', age: '3–4 سنوات', description: 'التعرف على 2 والعد إلى 2.', learnTitle: 'نتعرف على 2', explanation: 'الرقم 2 يمثل شيئين ويمكننا عد الأشياء واحداً ثم اثنين.', examples: ['2 كرتين', '2 نجمتين'], extra: [const TraceActivityConfig(2), const DragCountActivityConfig(2)], quiz: [_q('كم نجمة نحتاج لتمثيل 2؟', ['1', '2', '3'], 1), _q('ما الرقم بعد 1؟', ['0', '2', '3'], 1)]),
    _unit(n: 4, title: 'الرقم 3', age: '3–4 سنوات', description: 'التعرف على 3 والعد والمطابقة.', learnTitle: 'نتعرف على 3', explanation: 'نعد: 1 ثم 2 ثم 3، والعدد الأخير يخبرنا عن الكمية كلها.', examples: ['3 كرات', '3 كتب'], extra: [const TraceActivityConfig(3), const DragCountActivityConfig(3)], quiz: [_q('ما الرقم الذي يأتي بعد 2؟', ['1', '3', '4'], 1), _q('كم كرة تمثل 3؟', ['2', '3', '4'], 1)]),
    _unit(n: 5, title: 'الرقم 4', age: '3–4 سنوات', description: 'التعرف على 4 وعد أربع وحدات.', learnTitle: 'نتعرف على 4', explanation: 'أربع وحدات تعني العدد 4.', examples: ['4 أقلام', '4 مكعبات'], extra: [const TraceActivityConfig(4), const DragCountActivityConfig(4)], quiz: [_q('ما الرقم الذي يأتي بعد 3؟', ['2', '4', '5'], 1), _q('أي كمية تمثل 4؟', ['3', '4', '5'], 1)]),
    _unit(n: 6, title: 'الرقم 5', age: '3–4 سنوات', description: 'التعرف على 5 والعد حتى 5.', learnTitle: 'نتعرف على 5', explanation: 'خمسة أشياء تعني العدد 5، ويمكن استخدام أصابع اليد لتمثيله.', examples: ['5 أصابع', '5 نجوم'], extra: [const TraceActivityConfig(5), const DragCountActivityConfig(5)], quiz: [_q('ما الرقم بعد 4؟', ['3', '5', '6'], 1), _q('كم إصبعاً في اليد الواحدة؟', ['4', '5', '6'], 1)]),
    _unit(n: 7, title: 'مراجعة 0–5', age: '3–4 سنوات', description: 'مراجعة التعرف والعد والمطابقة والتتبع من 0 إلى 5.', learnTitle: 'نراجع معاً', explanation: 'نراجع الأرقام من 0 إلى 5، ونربط كل رقم بكمية مناسبة.', examples: ['0، 1، 2، 3، 4، 5'], extra: [const MatchingActivityConfig([MatchPairSpec(id: '0', leftType: MatchContentType.number, leftValue: 0, rightType: MatchContentType.quantity, rightValue: 0), MatchPairSpec(id: '3', leftType: MatchContentType.number, leftValue: 3, rightType: MatchContentType.quantity, rightValue: 3), MatchPairSpec(id: '5', leftType: MatchContentType.number, leftValue: 5, rightType: MatchContentType.quantity, rightValue: 5)]), const ComparisonActivityConfig(leftCount: 2, rightCount: 5, question: ComparisonQuestionType.fewer)], quiz: [_q('أي رقم أكبر؟', ['2', '5', '1'], 1), _q('ما الرقم بين 3 و5؟', ['2', '4', '6'], 1)]),

    // ================================================================
    // المرحلة 2 — 6–10 | 4–6 سنوات
    // ================================================================
    _unit(n: 8, title: 'الرقم 6', age: '4–6 سنوات', description: 'التعرف على 6 والعد والمطابقة.', learnTitle: 'نتعرف على 6', explanation: 'نضيف واحداً إلى 5 لنصل إلى 6.', examples: ['5 + 1 = 6'], extra: [const TraceActivityConfig(6), const DragCountActivityConfig(6)], quiz: [_q('ما الرقم بعد 5؟', ['4', '6', '7'], 1), _q('5 + 1 يساوي؟', ['5', '6', '7'], 1)]),
    _unit(n: 9, title: 'الرقم 7', age: '4–6 سنوات', description: 'التعرف على 7 ومقارنته بالأعداد السابقة.', learnTitle: 'نتعرف على 7', explanation: 'سبع وحدات تمثل العدد 7.', examples: ['6 + 1 = 7'], extra: [const TraceActivityConfig(7), const DragCountActivityConfig(7)], quiz: [_q('ما الرقم بعد 6؟', ['5', '7', '8'], 1), _q('أي عدد أكبر؟', ['7', '4', '3'], 0)]),
    _unit(n: 10, title: 'الرقم 8', age: '4–6 سنوات', description: 'التعرف على 8 والعد والمقارنة.', learnTitle: 'نتعرف على 8', explanation: 'ثماني وحدات تمثل العدد 8.', examples: ['7 + 1 = 8'], extra: [const TraceActivityConfig(8), const DragCountActivityConfig(8)], quiz: [_q('ما الرقم بعد 7؟', ['6', '8', '9'], 1), _q('8 أكبر من؟', ['9', '7', '10'], 1)]),
    _unit(n: 11, title: 'الرقم 9', age: '4–6 سنوات', description: 'التعرف على 9 والاستعداد للعدد 10.', learnTitle: 'نتعرف على 9', explanation: 'تسع وحدات تمثل العدد 9، والعدد التالي هو 10.', examples: ['8 + 1 = 9'], extra: [const TraceActivityConfig(9), const DragCountActivityConfig(9)], quiz: [_q('ما الرقم قبل 10؟', ['8', '9', '11'], 1), _q('8 + 1 يساوي؟', ['7', '9', '10'], 1)]),
    _unit(n: 12, title: 'العدد 10', age: '4–6 سنوات', description: 'فهم 10 كمجموعة كاملة من عشرة وحدات.', learnTitle: 'ما هي العشرة؟', explanation: 'عندما نجمع 10 وحدات نحصل على مجموعة من عشرة. الصفر في 10 يمثل عدم وجود آحاد إضافية.', examples: ['10 أصابع', '10 مكعبات'], extra: [const DragCountActivityConfig(10)], quiz: [_q('كم وحدة في عشرة واحدة؟', ['8', '9', '10'], 2), _q('ما الرقم بعد 9؟', ['8', '10', '11'], 1)]),
    _unit(n: 13, title: 'مراجعة 0–10', age: '4–6 سنوات', description: 'تثبيت العد والترتيب والمقارنة والكمية من 0 إلى 10.', learnTitle: 'اختبار الاستعداد', explanation: 'نراجع الأعداد من 0 إلى 10 قبل الانتقال إلى الأعداد ذات الخانتين.', examples: ['0، 2، 5، 8، 10'], extra: [const ComparisonActivityConfig(leftCount: 3, rightCount: 8, question: ComparisonQuestionType.more), const MatchingActivityConfig([MatchPairSpec(id: '2', leftType: MatchContentType.number, leftValue: 2, rightType: MatchContentType.quantity, rightValue: 2), MatchPairSpec(id: '10', leftType: MatchContentType.number, leftValue: 10, rightType: MatchContentType.quantity, rightValue: 10)])], quiz: [_q('ما العدد بعد 8؟', ['7', '9', '10'], 1), _q('أي عدد أكبر؟', ['4', '10', '6'], 1)]),

    // ================================================================
    // المرحلة 3 — العشرات حتى 100 | 5–7 سنوات
    // ================================================================
    _unit(n: 14, title: 'الآحاد والعشرات', age: '5–7 سنوات', description: 'فهم القيمة المكانية للآحاد والعشرات.', learnTitle: 'مكان الرقم مهم', explanation: 'في العدد ذي الخانتين، الخانة اليمنى للآحاد والخانة التي قبلها للعشرات.', examples: ['24 = 2 عشرات و4 آحاد', '50 = 5 عشرات و0 آحاد'], quiz: [_q('في 24 كم عشرة؟', ['2', '4', '24'], 0), _q('ما قيمة 4 في 24؟', ['4', '40', '24'], 0)]),
    _unit(n: 15, title: 'الأعداد 11–20', age: '5–7 سنوات', description: 'بناء وقراءة الأعداد من 11 إلى 20.', learnTitle: 'من 11 إلى 20', explanation: 'نبدأ بعشرة واحدة ثم نضيف الآحاد.', examples: ['11 = 10 + 1', '17 = 10 + 7', '20 = 2 عشرات'], extra: [const ArithmeticActivityConfig(operation: '+', questions: [ArithmeticQuestion(questionAr: '10 + 3 = ؟', correctAnswer: 13), ArithmeticQuestion(questionAr: '10 + 7 = ؟', correctAnswer: 17)])], quiz: [_q('10 + 3 يساوي؟', ['12', '13', '14'], 1), _q('20 فيها كم عشرة؟', ['1', '2', '20'], 1)]),
    _unit(n: 16, title: 'الأعداد 21–30', age: '5–7 سنوات', description: 'قراءة وبناء الأعداد من 21 إلى 30.', learnTitle: 'نبني العدد', explanation: 'نفكك العدد إلى عشرات وآحاد ثم نعيد تركيبه.', examples: ['24 = 20 + 4', '30 = 3 عشرات'], extra: [const ArithmeticActivityConfig(operation: '+', questions: [ArithmeticQuestion(questionAr: '20 + 4 = ؟', correctAnswer: 24), ArithmeticQuestion(questionAr: '20 + 8 = ؟', correctAnswer: 28)])], quiz: [_q('24 فيها كم آحاد؟', ['2', '4', '20'], 1), _q('20 + 8 يساوي؟', ['18', '28', '30'], 1)]),
    _unit(n: 17, title: 'الأعداد 31–50', age: '5–7 سنوات', description: 'قراءة وتحليل الأعداد حتى 50.', learnTitle: 'نوسع العدد', explanation: 'نقرأ العشرات ثم الآحاد ونكتب العدد بصورة صحيحة.', examples: ['34 = 30 + 4', '47 = 40 + 7'], extra: [const ArithmeticActivityConfig(operation: '+', questions: [ArithmeticQuestion(questionAr: '30 + 4 = ؟', correctAnswer: 34), ArithmeticQuestion(questionAr: '40 + 7 = ؟', correctAnswer: 47)])], quiz: [_q('34 فيها كم عشرة؟', ['3', '4', '34'], 0), _q('40 + 7 يساوي؟', ['47', '74', '37'], 0)]),
    _unit(n: 18, title: 'الأعداد 51–70', age: '5–7 سنوات', description: 'قراءة وترتيب الأعداد من 51 إلى 70.', learnTitle: 'العشرات الجديدة', explanation: 'ننتقل من 5 عشرات إلى 6 ثم 7 عشرات مع تغيير الآحاد.', examples: ['58 = 50 + 8', '70 = 7 عشرات'], quiz: [_q('58 = ؟', ['50 + 8', '5 + 8', '80 + 5'], 0), _q('أي عدد أكبر؟', ['61', '16', '60'], 0)]),
    _unit(n: 19, title: 'الأعداد 71–100', age: '5–7 سنوات', description: 'إتقان الأعداد حتى 100 والعد بالعشرات.', learnTitle: 'نصل إلى 100', explanation: 'بعد 90 تأتي الأعداد 91 إلى 99 ثم 100، وهو عشرة عشرات.', examples: ['80، 90، 100', '99 ثم 100'], extra: [const ArithmeticActivityConfig(operation: '+', questions: [ArithmeticQuestion(questionAr: '90 + 9 = ؟', correctAnswer: 99), ArithmeticQuestion(questionAr: '90 + 10 = ؟', correctAnswer: 100)])], quiz: [_q('ما العدد بعد 99؟', ['98', '100', '101'], 1), _q('100 فيها كم عشرة؟', ['5', '10', '100'], 1)]),
    _unit(n: 20, title: 'المقارنة والترتيب حتى 100', age: '6–8 سنوات', description: 'مقارنة وترتيب الأعداد باستخدام العشرات والآحاد.', learnTitle: 'أيهما أكبر؟', explanation: 'نقارن العشرات أولاً، وإذا تساوت نقارن الآحاد.', examples: ['63 > 36', '79 < 80', '45 = 45'], quiz: [_q('أي عدد أكبر؟', ['36', '63', '26'], 1), _q('79 مقارنة بـ80؟', ['أكبر', 'أصغر', 'يساوي'], 1)]),
    _unit(n: 21, title: 'مراجعة واختبار الأعداد حتى 100', age: '6–8 سنوات', description: 'مراجعة القيمة المكانية والعد والمقارنة والترتيب حتى 100.', learnTitle: 'مراجعة 0–100', explanation: 'نثبت فهم الآحاد والعشرات والقراءة والمقارنة قبل الانتقال إلى المئات.', examples: ['58 = 50 + 8', '100 = 10 عشرات'], extra: [const ReviewActivityConfig(titleAr: 'مراجعة الأعداد حتى 100', questions: [_q('كم عشرة في 70؟', ['7', '70', '0'], 0), _q('أي عدد أكبر؟', ['89', '98', '88'], 1)])], quiz: [_q('50 + 8 يساوي؟', ['58', '85', '50'], 0), _q('ما العدد قبل 100؟', ['98', '99', '101'], 1)]),

    // ================================================================
    // المرحلة 4 — المئات | 7–9 سنوات
    // ================================================================
    _unit(n: 22, title: 'مفهوم المئة', age: '7–9 سنوات', description: 'فهم 100 كوحدة من عشر عشرات.', learnTitle: 'ما هي المئة؟', explanation: 'المئة تساوي 10 عشرات وتساوي 100 وحدة.', examples: ['100 = 10 عشرات', '100 = 100 وحدة'], quiz: [_q('100 تساوي كم عشرة؟', ['1', '10', '100'], 1), _q('أي عدد يمثل مئة؟', ['10', '100', '1000'], 1)]),
    _unit(n: 23, title: 'الأعداد 101–200', age: '7–9 سنوات', description: 'قراءة وبناء الأعداد من 101 إلى 200.', learnTitle: 'المئات مع الآحاد والعشرات', explanation: 'العدد من ثلاث خانات يتكون من مئات وعشرات وآحاد.', examples: ['124 = 1 مئة + 2 عشرات + 4 آحاد', '200 = 2 مئات'], quiz: [_q('في 124 كم مئة؟', ['1', '2', '4'], 0), _q('124 = ؟', ['100 + 20 + 4', '10 + 20 + 4', '100 + 2 + 4'], 0)]),
    _unit(n: 24, title: 'الأعداد 201–500', age: '7–9 سنوات', description: 'تحليل الأعداد ذات الثلاث خانات حتى 500.', learnTitle: 'نبني المئات', explanation: 'نحدد قيمة كل خانة ثم نقرأ العدد كاملاً.', examples: ['305 = 3 مئات + 0 عشرات + 5 آحاد', '450 = 4 مئات + 5 عشرات'], quiz: [_q('في 450 كم عشرة؟', ['4', '5', '0'], 1), _q('305 = ؟', ['300 + 5', '30 + 5', '300 + 50'], 0)]),
    _unit(n: 25, title: 'الأعداد 501–999', age: '7–9 سنوات', description: 'قراءة وتحليل الأعداد حتى 999.', learnTitle: 'نقترب من 1000', explanation: 'نقرأ المئات ثم العشرات ثم الآحاد، وننتبه إلى الخانات التي قيمتها 0.', examples: ['608 = 600 + 8', '999 = 900 + 90 + 9'], quiz: [_q('608 = ؟', ['600 + 8', '60 + 8', '600 + 80'], 0), _q('ما العدد بعد 999؟', ['998', '1000', '100'], 1)]),
    _unit(n: 26, title: 'القيمة المكانية حتى 999', age: '7–9 سنوات', description: 'إتقان المئات والعشرات والآحاد.', learnTitle: 'قيمة كل خانة', explanation: 'قيمة الرقم تعتمد على مكانه: آحاد، عشرات، أو مئات.', examples: ['572 = 500 + 70 + 2', '707 = 700 + 7'], quiz: [_q('ما قيمة 7 في 572؟', ['7', '70', '700'], 1), _q('ما قيمة 7 في 707 في خانة المئات؟', ['7', '70', '700'], 2)]),
    _unit(n: 27, title: 'مقارنة وترتيب المئات', age: '7–9 سنوات', description: 'مقارنة وترتيب الأعداد حتى 999.', learnTitle: 'نقارن من اليسار', explanation: 'نقارن المئات، ثم العشرات، ثم الآحاد عند الحاجة.', examples: ['450 < 500', '720 > 702'], quiz: [_q('أي عدد أكبر؟', ['450', '540', '405'], 1), _q('720 مقارنة بـ702؟', ['أصغر', 'أكبر', 'يساوي'], 1)]),

    // ================================================================
    // المرحلة 5 — الآلاف | 8–11 سنة
    // ================================================================
    _unit(n: 28, title: 'مفهوم الألف', age: '8–11 سنة', description: 'فهم 1000 كوحدة تساوي 10 مئات.', learnTitle: 'ما هو 1000؟', explanation: 'الألف تساوي 10 مئات و100 عشرات و1000 وحدة.', examples: ['1000 = 10 مئات', '1000 = 1000 وحدة'], quiz: [_q('1000 تساوي كم مئة؟', ['1', '10', '100'], 1), _q('ما العدد الذي يمثل ألفاً؟', ['100', '1000', '10000'], 1)]),
    _unit(n: 29, title: 'الأعداد 1001–1999', age: '8–11 سنة', description: 'قراءة وبناء الأعداد ذات الأربع خانات.', learnTitle: 'الآلاف والمئات والعشرات والآحاد', explanation: 'أربع خانات تعني آلافاً ومئات وعشرات وآحاداً.', examples: ['1245 = 1000 + 200 + 40 + 5', '1500 = 1 ألف + 5 مئات'], quiz: [_q('1245 فيها كم ألف؟', ['1', '2', '4'], 0), _q('1245 = ؟', ['1000 + 200 + 40 + 5', '100 + 20 + 4 + 5', '1000 + 20 + 45'], 0)]),
    _unit(n: 30, title: 'الأعداد 2000–4999', age: '8–11 سنة', description: 'قراءة وتحليل أعداد الآلاف حتى 4999.', learnTitle: 'نبني الآلاف', explanation: 'نقرأ رقم الآلاف ثم باقي الخانات حسب القيمة المكانية.', examples: ['2345 = 2000 + 300 + 40 + 5', '4000 = 4 آلاف'], quiz: [_q('2345 فيها كم ألف؟', ['2', '3', '4'], 0), _q('4000 = ؟', ['4 مئات', '4 آلاف', '40 ألفاً'], 1)]),
    _unit(n: 31, title: 'الأعداد 5000–9999', age: '8–11 سنة', description: 'قراءة وتحليل الأعداد حتى 9999.', learnTitle: 'حتى 9999', explanation: 'نستخدم خانات الآلاف والمئات والعشرات والآحاد لقراءة العدد.', examples: ['5820 = 5000 + 800 + 20', '9999 = 9000 + 900 + 90 + 9'], quiz: [_q('5820 = ؟', ['5000 + 800 + 20', '500 + 80 + 20', '5000 + 80 + 2'], 0), _q('ما العدد الأكبر؟', ['8999', '9899', '9998'], 2)]),
    _unit(n: 32, title: 'القيمة المكانية حتى 9999', age: '8–11 سنة', description: 'إتقان الآلاف والمئات والعشرات والآحاد.', learnTitle: 'الخانات الأربع', explanation: 'كل خانة لها قيمة: آلاف، مئات، عشرات، آحاد.', examples: ['5724 = 5000 + 700 + 20 + 4'], quiz: [_q('ما قيمة 7 في 5724؟', ['7', '70', '700'], 2), _q('ما قيمة 5 في 5724؟', ['5', '500', '5000'], 2)]),
    _unit(n: 33, title: 'مقارنة وترتيب الأعداد حتى 9999', age: '8–11 سنة', description: 'مقارنة وترتيب أعداد متعددة الخانات.', learnTitle: 'نقارن الخانات', explanation: 'نبدأ من خانة الآلاف ثم المئات ثم العشرات ثم الآحاد.', examples: ['5200 > 4999', '7020 > 7002'], quiz: [_q('أي عدد أكبر؟', ['5200', '5020', '2500'], 0), _q('7020 مقارنة بـ7002؟', ['أصغر', 'أكبر', 'يساوي'], 1)]),
    _unit(n: 34, title: 'مراجعة واختبار الأعداد حتى 9999', age: '8–11 سنة', description: 'مراجعة شاملة قبل العمليات الأربع.', learnTitle: 'اختبار الاستعداد للحساب', explanation: 'نثبت فهم القيمة المكانية والقراءة والمقارنة قبل البدء بالعمليات.', examples: ['2345 = 2000 + 300 + 40 + 5'], extra: [const ReviewActivityConfig(titleAr: 'مراجعة الآلاف', questions: [_q('ما قيمة 3 في 2345؟', ['3', '30', '300'], 2), _q('أي عدد أكبر؟', ['4321', '4231', '4312'], 0)])], quiz: [_q('2345 فيها كم مئة؟', ['2', '3', '4'], 1), _q('ما العدد بعد 9999؟', ['9998', '10000', '999'], 1)]),

    // ================================================================
    // المرحلة 6 — العمليات الأربع | 9–12 سنة
    // ================================================================
    _unit(n: 35, title: 'الجمع بدون حمل', age: '9–12 سنة', description: 'جمع أعداد صحيحة مع المحافظة على القيمة المكانية.', learnTitle: 'الجمع يعني إضافة', explanation: 'في الجمع نضم الكميات معاً، ونبدأ من الآحاد ثم ننتقل إلى الخانات الأعلى.', examples: ['23 + 14 = 37', '120 + 230 = 350'], extra: [const ArithmeticActivityConfig(operation: '+', questions: [ArithmeticQuestion(questionAr: '23 + 14 = ؟', correctAnswer: 37), ArithmeticQuestion(questionAr: '120 + 230 = ؟', correctAnswer: 350)])], quiz: [_q('23 + 14 = ؟', ['37', '27', '47'], 0), _q('120 + 230 = ؟', ['250', '350', '360'], 1)]),
    _unit(n: 36, title: 'الجمع مع الحمل', age: '9–12 سنة', description: 'الجمع العمودي مع إعادة التجميع.', learnTitle: 'عندما تتجاوز الآحاد 9', explanation: 'إذا أصبح مجموع الآحاد 10 أو أكثر، نعيد تجميع عشرة آحاد في خانة العشرات.', examples: ['27 + 15 = 42', '58 + 27 = 85'], extra: [const ArithmeticActivityConfig(operation: '+', questions: [ArithmeticQuestion(questionAr: '27 + 15 = ؟', correctAnswer: 42), ArithmeticQuestion(questionAr: '58 + 27 = ؟', correctAnswer: 85)])], quiz: [_q('27 + 15 = ؟', ['32', '42', '52'], 1), _q('58 + 27 = ؟', ['75', '85', '95'], 1)]),
    _unit(n: 37, title: 'مسائل الجمع', age: '9–12 سنة', description: 'اختيار عملية الجمع وحل مسائل لفظية.', learnTitle: 'الجمع في الحياة', explanation: 'نستخدم الجمع عندما نضم كميتين أو أكثر لمعرفة المجموع.', examples: ['لدى أحمد 12 قلماً وأعطاه صديقه 8 أقلام: 20 قلماً'], extra: [const WordProblemActivityConfig([ArithmeticQuestion(questionAr: 'لدى سارة 12 كتاباً واشترت 8 كتب. كم كتاباً لديها؟', correctAnswer: 20), ArithmeticQuestion(questionAr: 'في صندوق 25 كرة أضيفت 15 كرة. كم أصبحت؟', correctAnswer: 40)])], quiz: [_q('12 + 8 = ؟', ['18', '20', '22'], 1), _q('25 + 15 = ؟', ['30', '40', '50'], 1)]),
    _unit(n: 38, title: 'الطرح بدون استلاف', age: '9–12 سنة', description: 'طرح أعداد صحيحة بدون إعادة تجميع.', learnTitle: 'الطرح يعني إزالة أو إيجاد الفرق', explanation: 'نطرح عندما نزيل جزءاً من الكمية أو نبحث عن الفرق بين عددين.', examples: ['45 - 12 = 33', '80 - 30 = 50'], extra: [const ArithmeticActivityConfig(operation: '-', questions: [ArithmeticQuestion(questionAr: '45 - 12 = ؟', correctAnswer: 33), ArithmeticQuestion(questionAr: '80 - 30 = ؟', correctAnswer: 50)])], quiz: [_q('45 - 12 = ؟', ['23', '33', '43'], 1), _q('80 - 30 = ؟', ['40', '50', '60'], 1)]),
    _unit(n: 39, title: 'الطرح مع الاستلاف', age: '9–12 سنة', description: 'الطرح مع إعادة التجميع بين الخانات.', learnTitle: 'عندما نحتاج إلى الاستلاف', explanation: 'إذا كان رقم الآحاد في العدد الأول أصغر من الآحاد المطروحة، نعيد تجميع عشرة من العشرات.', examples: ['42 - 17 = 25', '100 - 36 = 64'], extra: [const ArithmeticActivityConfig(operation: '-', questions: [ArithmeticQuestion(questionAr: '42 - 17 = ؟', correctAnswer: 25), ArithmeticQuestion(questionAr: '100 - 36 = ؟', correctAnswer: 64)])], quiz: [_q('42 - 17 = ؟', ['25', '35', '45'], 0), _q('100 - 36 = ؟', ['54', '64', '74'], 1)]),
    _unit(n: 40, title: 'مسائل الطرح', age: '9–12 سنة', description: 'تطبيق الطرح على مسائل لفظية واختيار العملية المناسبة.', learnTitle: 'نستخدم الطرح', explanation: 'إذا نقصت كمية أو أردنا معرفة ما تبقى أو الفرق، نستخدم الطرح.', examples: ['لدى علي 30 درهماً أنفق 12: الباقي 18'], extra: [const WordProblemActivityConfig([ArithmeticQuestion(questionAr: 'لدى علي 30 درهماً أنفق 12. كم بقي؟', correctAnswer: 18), ArithmeticQuestion(questionAr: 'في المكتبة 50 كتاباً استعار الطلاب 23. كم بقي؟', correctAnswer: 27)])], quiz: [_q('30 - 12 = ؟', ['18', '20', '22'], 0), _q('50 - 23 = ؟', ['17', '27', '37'], 1)]),
    _unit(n: 41, title: 'مفهوم الضرب', age: '9–12 سنة', description: 'فهم الضرب كمجموعات متساوية.', learnTitle: 'الضرب تكرار للجمع', explanation: 'الضرب يساعدنا على جمع مجموعات متساوية بسرعة.', examples: ['3 × 4 يعني 3 مجموعات من 4', '4 + 4 + 4 = 12'], extra: [const ArithmeticActivityConfig(operation: '×', questions: [ArithmeticQuestion(questionAr: '3 × 4 = ؟', correctAnswer: 12), ArithmeticQuestion(questionAr: '5 × 2 = ؟', correctAnswer: 10)])], quiz: [_q('3 × 4 = ؟', ['7', '12', '16'], 1), _q('5 × 2 = ؟', ['7', '10', '12'], 1)]),
    _unit(n: 42, title: 'جداول الضرب 2–10', age: '9–12 سنة', description: 'بناء وإتقان جداول الضرب تدريجياً.', learnTitle: 'نتعلم الجداول', explanation: 'نتدرب على الضرب من 2 إلى 10 ونبحث عن الأنماط التي تساعد على التذكر.', examples: ['2 × 5 = 10', '7 × 3 = 21', '10 × 4 = 40'], extra: [const ArithmeticActivityConfig(operation: '×', questions: [ArithmeticQuestion(questionAr: '7 × 3 = ؟', correctAnswer: 21), ArithmeticQuestion(questionAr: '8 × 4 = ؟', correctAnswer: 32)])], quiz: [_q('7 × 3 = ؟', ['18', '21', '24'], 1), _q('8 × 4 = ؟', ['28', '32', '36'], 1)]),
    _unit(n: 43, title: 'الضرب العمودي', age: '9–12 سنة', description: 'ضرب أعداد متعددة الخانات باستخدام القيمة المكانية.', learnTitle: 'نضرب خانة بخانة', explanation: 'نرتب الأعداد ونضرب الآحاد ثم العشرات ثم نجمع النتائج الجزئية.', examples: ['23 × 4 = 92', '12 × 11 = 132'], extra: [const ArithmeticActivityConfig(operation: '×', questions: [ArithmeticQuestion(questionAr: '23 × 4 = ؟', correctAnswer: 92), ArithmeticQuestion(questionAr: '12 × 11 = ؟', correctAnswer: 132)])], quiz: [_q('23 × 4 = ؟', ['82', '92', '102'], 1), _q('12 × 11 = ؟', ['122', '132', '142'], 1)]),
    _unit(n: 44, title: 'مفهوم القسمة', age: '9–12 سنة', description: 'فهم القسمة كتوزيع متساو ومجموعات.', learnTitle: 'القسمة توزيع عادل', explanation: 'القسمة تجيب عن سؤال: كيف نوزع كمية بالتساوي؟', examples: ['12 ÷ 3 = 4', '20 ÷ 5 = 4'], extra: [const ArithmeticActivityConfig(operation: '÷', questions: [ArithmeticQuestion(questionAr: '12 ÷ 3 = ؟', correctAnswer: 4), ArithmeticQuestion(questionAr: '20 ÷ 5 = ؟', correctAnswer: 4)])], quiz: [_q('12 ÷ 3 = ؟', ['3', '4', '5'], 1), _q('20 ÷ 5 = ؟', ['3', '4', '5'], 1)]),
    _unit(n: 45, title: 'القسمة مع الباقي والقسمة المطولة', age: '9–12 سنة', description: 'القسمة مع وبدون باق وتطبيق الخوارزمية على أعداد أكبر.', learnTitle: 'نقسم خطوة خطوة', explanation: 'عند عدم انقسام العدد تماماً يظهر الباقي، وفي الأعداد الأكبر نستخدم القسمة المطولة.', examples: ['14 ÷ 3 = 4 والباقي 2', '84 ÷ 4 = 21'], extra: [const ArithmeticActivityConfig(operation: '÷', questions: [ArithmeticQuestion(questionAr: '14 ÷ 3 = ؟', correctAnswerText: '4 والباقي 2'), ArithmeticQuestion(questionAr: '84 ÷ 4 = ؟', correctAnswer: 21)])], quiz: [_q('14 ÷ 3 = ؟', ['4 والباقي 1', '4 والباقي 2', '5 والباقي 1'], 1), _q('84 ÷ 4 = ؟', ['19', '21', '24'], 1)]),
    _unit(n: 46, title: 'مسائل العمليات الأربع', age: '9–12 سنة', description: 'اختيار العملية المناسبة وحل مسائل متعددة الخطوات.', learnTitle: 'أي عملية نختار؟', explanation: 'نحدد هل المسألة تتحدث عن إضافة أو نقصان أو مجموعات متساوية أو توزيع قبل الحساب.', examples: ['الجمع للزيادة', 'الطرح للنقصان', 'الضرب للمجموعات المتساوية', 'القسمة للتوزيع'], extra: [const WordProblemActivityConfig([ArithmeticQuestion(questionAr: 'لدى متجر 6 صناديق في كل صندوق 8 ألعاب. كم لعبة؟', correctAnswer: 48), ArithmeticQuestion(questionAr: '48 لعبة وزعت بالتساوي على 6 أطفال. كم لكل طفل؟', correctAnswer: 8)])], quiz: [_q('6 × 8 = ؟', ['42', '48', '54'], 1), _q('48 ÷ 6 = ؟', ['6', '8', '10'], 1)]),

    // ================================================================
    // المرحلة 7 — الكسور والعشريات | 10–13 سنة
    // ================================================================
    _unit(n: 47, title: 'مفهوم الكسر', age: '10–13 سنة', description: 'فهم الجزء من الكل والبسط والمقام.', learnTitle: 'ما هو الكسر؟', explanation: 'الكسر يصف جزءاً من كل مقسم إلى أجزاء متساوية. العدد العلوي هو البسط والسفلي هو المقام.', examples: ['1/2 نصف', '3/4 ثلاثة أرباع'], quiz: [_q('في 3/4 ما البسط؟', ['3', '4', '7'], 0), _q('في 3/4 ما المقام؟', ['3', '4', '1'], 1)]),
    _unit(n: 48, title: 'الكسور المتكافئة والمقارنة', age: '10–13 سنة', description: 'التعرف على الكسور المتكافئة ومقارنة الكسور.', learnTitle: 'يمكن أن نكتب الجزء بطرق مختلفة', explanation: 'الكسور المتكافئة تمثل الكمية نفسها، ويمكن المقارنة باستخدام مقام مشترك أو تمثيل بصري.', examples: ['1/2 = 2/4', '1/4 < 3/4'], quiz: [_q('أي كسر يكافئ 1/2؟', ['1/3', '2/4', '3/4'], 1), _q('أي كسر أكبر؟', ['1/4', '3/4', '2/4'], 1)]),
    _unit(n: 49, title: 'العمليات على الكسور', age: '10–13 سنة', description: 'جمع وطرح وضرب وقسمة الكسور تدريجياً.', learnTitle: 'نحسب بالكسور', explanation: 'نجمع ونطرح الكسور بالمقامات المناسبة، ونضرب ونقسم وفق القواعد، مع تبسيط الناتج عند الحاجة.', examples: ['1/4 + 1/4 = 1/2', '2/3 × 3 = 2'], extra: [const MultipleChoiceActivityConfig([_q('1/4 + 1/4 = ؟', ['1/2', '1/4', '1'], 0), _q('2/4 بعد التبسيط؟', ['1/2', '1/4', '2'], 0)])], quiz: [_q('1/4 + 1/4 = ؟', ['1/2', '1/4', '3/4'], 0), _q('2/4 = ؟', ['1/2', '1/3', '2'], 0)]),
    _unit(n: 50, title: 'الأعداد العشرية', age: '10–13 سنة', description: 'فهم القيمة المكانية بعد الفاصلة وقراءة الأعداد العشرية.', learnTitle: 'ما بعد الفاصلة', explanation: 'الأرقام بعد الفاصلة تمثل أجزاء من الواحد مثل الأعشار والأجزاء من مئة.', examples: ['0.5 = 5/10', '1.25 = 1 + 25/100'], quiz: [_q('0.5 يساوي أي كسر؟', ['1/2', '1/5', '5/100'], 0), _q('ما قيمة 5 في 1.25؟', ['5 أعشار', '5 أجزاء من مئة', '5 آحاد'], 1)]),
    _unit(n: 51, title: 'العمليات على الأعداد العشرية', age: '10–13 سنة', description: 'الجمع والطرح والضرب والقسمة على الأعداد العشرية.', learnTitle: 'نحسب بالعشريات', explanation: 'نرتب الفاصلة العشرية عند الجمع والطرح، ونطبق قواعد الضرب والقسمة المناسبة.', examples: ['1.2 + 0.3 = 1.5', '2.5 - 0.5 = 2'], extra: [const ArithmeticActivityConfig(operation: '+', questions: [ArithmeticQuestion(questionAr: '1.2 + 0.3 = ؟', correctAnswer: 1.5), ArithmeticQuestion(questionAr: '2.5 - 0.5 = ؟', correctAnswer: 2)])], quiz: [_q('1.2 + 0.3 = ؟', ['1.3', '1.5', '1.7'], 1), _q('2.5 - 0.5 = ؟', ['1', '2', '3'], 1)]),

    // ================================================================
    // المرحلة 8 + 9 — النسب والتناسب والجبر | 12–16 سنة
    // ================================================================
    _unit(n: 52, title: 'النسب والتناسب والجبر والمعادلات والمتباينات', age: '12–16 سنة', description: 'وحدة ختامية واسعة تجمع النسبة والتناسب والنسبة المئوية ومبادئ الجبر والمعادلات والمتباينات.', learnTitle: 'من الحساب إلى الجبر', explanation: 'نتعلم كيف نمثل العلاقات بالأرقام والرموز، ونستخدم المتغيرات والمعادلات والمتباينات لحل مسائل جديدة.', examples: ['2:3 نسبة', '2/3 = 4/6 تناسب', 'x + 3 = 7', 'x > 4'], extra: [const LessonActivityConfig(titleAr: 'النسبة والتناسب', explanationAr: 'النسبة تقارن كميتين، والتناسب يصف تساوي نسبتين. يمكن تحويل النسبة المئوية إلى كسر أو عدد عشري والعكس.', examplesAr: ['2:3', '50% = 1/2', '2/3 = 4/6']), const MultipleChoiceActivityConfig([_q('50% يساوي؟', ['1/2', '1/4', '2/5'], 0), _q('إذا كان x + 3 = 7 فما قيمة x؟', ['3', '4', '5'], 1), _q('إذا كان x > 4 فأي عدد يمكن أن يكون x؟', ['2', '4', '6'], 2)]), const ReviewActivityConfig(titleAr: 'مراجعة النسبة والجبر', questions: [_q('2/3 = 4/6 هل العبارتان متناسبتان؟', ['نعم', 'لا'], 0), _q('x + 3 = 7، قيمة x؟', ['3', '4', '10'], 1)])], quiz: [_q('50% يساوي؟', ['1/2', '1/3', '1/4'], 0), _q('إذا كان x + 3 = 7، فما قيمة x؟', ['3', '4', '5'], 1), _q('إذا كان x > 4، فأي قيمة تحقق المتباينة؟', ['2', '4', '6'], 2)], assessment: [_q('2:3 هي؟', ['نسبة', 'كسر فقط', 'عملية ضرب'], 0), _q('50% = ؟', ['1/2', '1/4', '2/3'], 0), _q('x + 3 = 7، x = ؟', ['3', '4', '7'], 1), _q('x > 4، أي قيمة صحيحة؟', ['3', '4', '5'], 2)]),
  ];
}
