import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../core/audio/audio_service.dart';
import '../core/progress/progress_tracker.dart';
import '../core/progress/unit_progress.dart';
import '../core/theme/game_theme.dart';
import '../core/theme/responsive.dart';
import '../models/stage_reward.dart';
import '../models/unit_model.dart';
import '../models/units_data.dart';
import '../widgets/game/journey_world_decoration.dart';
import '../widgets/shared/banner_ad_widget.dart';
import '../widgets/shared/game_celebration.dart';
import 'certificate_screen.dart';
import 'unit_player_screen.dart';

bool _isStageEnd(int order) => const {13, 20, 30, 38, 44, 46, 52}.contains(order);
bool _isStageStart(int order) => const {14, 21, 31, 39, 45, 47}.contains(order);
int _stageNumberForOrder(int order) {
  if (order <= 13) return 1;
  if (order <= 20) return 2;
  if (order <= 30) return 3;
  if (order <= 38) return 4;
  if (order <= 44) return 5;
  if (order <= 46) return 6;
  return 7;
}
_WorldInfo _worldFor(int order) {
  if (order <= 13) return const _WorldInfo('عالم الأعداد', GameTheme.ocean, GameTheme.mint, Icons.looks_one_rounded);
  if (order <= 20) return const _WorldInfo('وادي العشرات', GameTheme.mint, GameTheme.ocean, Icons.grid_3x3_rounded);
  if (order <= 34) return const _WorldInfo('مدينة المئات والآلاف', GameTheme.sunshine, GameTheme.mango, Icons.location_city_rounded);
  if (order <= 40) return const _WorldInfo('جزيرة الجمع والطرح', GameTheme.mango, GameTheme.coral, Icons.add_rounded);
  if (order <= 44) return const _WorldInfo('كوكب الضرب', GameTheme.coral, GameTheme.berry, Icons.close_rounded);
  if (order <= 46) return const _WorldInfo('كوكب القسمة', GameTheme.violet, GameTheme.berry, Icons.percent_rounded);
  return const _WorldInfo('مجرة الكسور والجبر', GameTheme.berry, GameTheme.violet, Icons.functions_rounded);
}

class UnitsMapScreen extends StatefulWidget { const UnitsMapScreen({super.key}); @override State<UnitsMapScreen> createState()=>_UnitsMapScreenState(); }
class _UnitsMapScreenState extends State<UnitsMapScreen> {
 final List<UnitModel> _units=UnitsData.units; String? _newlyUnlockedUnitId; int? _rewardCelebrationStage;
 Future<void> _openUnit(UnitModel unit) async { final before=ProgressTracker.instance.getCompletedUnitIds().toSet(); final learnerAge = LearnerProfile.age ?? 6; await Navigator.of(context).push(MaterialPageRoute(builder:(_)=>UnitPlayerScreen(unit:unit, learnerAge: learnerAge))); if(!mounted)return; final after=ProgressTracker.instance.getCompletedUnitIds().toSet(); final newlyCompleted=after.difference(before); UnitModel? newlyUnlocked; for(final id in newlyCompleted){final index=_units.indexWhere((u)=>u.id==id); if(index>=0&&index+1<_units.length){newlyUnlocked=_units[index+1];break;}} final id=newlyUnlocked?.id; setState(()=>_newlyUnlockedUnitId=id); if(newlyUnlocked!=null){await AudioService.instance.playUnlock(); if(!mounted)return; Future<void>.delayed(const Duration(milliseconds:2200),(){if(mounted&&_newlyUnlockedUnitId==id)setState(()=>_newlyUnlockedUnitId=null);});} }
 Future<void> _claimReward(StageRewardDefinition reward) async {final claimed=await ProgressTracker.instance.claimStageReward(reward.stage); if(!mounted)return; if(!claimed){setState((){});return;} setState(()=>_rewardCelebrationStage=reward.stage); await AudioService.instance.playUnlock(); if(!mounted)return; await showDialog<void>(context:context,builder:(_)=>_RewardCelebration(reward:reward)); if(mounted)setState(()=>_rewardCelebrationStage=null);}
 void _showReward(StageRewardDefinition reward){final status=ProgressTracker.instance.getStageRewardStatus(reward.stage); if(status==StageRewardStatus.available){_claimReward(reward);return;} showDialog<void>(context:context,builder:(_)=>AlertDialog(title:Text(reward.titleAr),content:Text(status==StageRewardStatus.claimed?'تم جمع هذه المكافأة وربطها بإنجاز المرحلة.':'أكمل جميع وحدات المرحلة ${reward.stage} أولاً لتفتح المكافأة.'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('حسناً'))]));}
 @override Widget build(BuildContext context){final completedCount=ProgressTracker.instance.getCompletedUnitIds().length;final progress=ProgressTracker.instance.getOverallProgress(_units.length);final nextUnit=ProgressTracker.instance.getNextUnit();final allCompleted=completedCount==_units.length;final mapItems=_buildMapItems();return Scaffold(backgroundColor:GameTheme.sky,appBar:AppBar(title:const Text('أرقامي · عالم الأرقام'),centerTitle:true,actions:[if(allCompleted)IconButton(tooltip:'شهادتك',icon:Image.asset('assets/game/rewards/trophy.png',width:25,height:25),onPressed:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>const CertificateScreen())))]),body:SafeArea(child:Column(children:[Responsive.constrainedCenter(child:_JourneyHeader(progress:progress,completedCount:completedCount,totalCount:_units.length,nextUnit:nextUnit,onContinue:nextUnit==null?null:()=>_openUnit(nextUnit),claimedRewards:ProgressTracker.instance.getClaimedStageRewards().length,totalRewards:StageRewards.all.length)),Expanded(child:Responsive.constrainedCenter(child:Stack(fit:StackFit.expand,children:[const JourneyWorldDecoration(),ListView.builder(padding:const EdgeInsets.fromLTRB(18,18,18,34),itemCount:mapItems.length,itemBuilder:(context,index){final item=mapItems[index];if(item is StageRewardDefinition){final status=ProgressTracker.instance.getStageRewardStatus(item.stage);return _StageRewardNode(reward:item,status:status,celebration:_rewardCelebrationStage==item.stage,onTap:()=>_showReward(item));}final unit=item as UnitModel;final unitIndex=_units.indexOf(unit);final unlocked=ProgressTracker.instance.isUnitUnlocked(unit.id);final unitProgress=ProgressTracker.instance.getUnitProgress(unit.id);final previousCompleted=unitIndex==0||ProgressTracker.instance.getUnitProgress(_units[unitIndex-1].id).completed;return _MapLevel(unit:unit,progress:unitProgress,unlocked:unlocked,previousCompleted:previousCompleted,highlight:unit.id==_newlyUnlockedUnitId,onTap:unlocked?()=>_openUnit(unit):null);})]))),const BannerAdWidget()])));}
 List<Object> _buildMapItems(){final items=<Object>[];for(final unit in _units){items.add(unit);if(_isStageEnd(unit.order))items.add(StageRewards.forStage(_stageNumberForOrder(unit.order)));}return items;}
}
class _JourneyHeader extends StatelessWidget{final double progress;final int completedCount,totalCount,claimedRewards,totalRewards;final UnitModel? nextUnit;final VoidCallback? onContinue;const _JourneyHeader({required this.progress,required this.completedCount,required this.totalCount,required this.nextUnit,required this.onContinue,required this.claimedRewards,required this.totalRewards});@override Widget build(BuildContext context)=>Card(margin:const EdgeInsets.fromLTRB(18,10,18,4),color:GameTheme.paper,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(GameTheme.cardRadius)),child:Padding(padding:const EdgeInsets.all(16),child:Column(children:[Row(children:[Image.asset('assets/game/rewards/trophy.png',width:44,height:44),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('رحلة الأرقام',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:2),Text('$completedCount من $totalCount محطات مكتملة')])),Text('${(progress*100).round()}%',style:Theme.of(context).textTheme.titleMedium?.copyWith(color:GameTheme.ocean,fontWeight:FontWeight.w900))]),const SizedBox(height:9),ClipRRect(borderRadius:BorderRadius.circular(10),child:LinearProgressIndicator(value:progress,minHeight:9,backgroundColor:GameTheme.ocean.withValues(alpha:.10),valueColor:const AlwaysStoppedAnimation(GameTheme.ocean))),const SizedBox(height:8),Text('مكافآت العوالم: $claimedRewards / $totalRewards'),if(nextUnit!=null)...[const SizedBox(height:9),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:onContinue,icon:const Icon(Icons.play_arrow_rounded),label:Text('تابع: ${nextUnit!.titleAr}')))]else... [const SizedBox(height:8),Text('أكملت عالم الأرقام كاملًا 🎉',style:Theme.of(context).textTheme.titleMedium?.copyWith(color:GameTheme.success,fontWeight:FontWeight.w800))]])));
}
class _MapLevel extends StatelessWidget{final UnitModel unit;final UnitProgress progress;final bool unlocked,previousCompleted,highlight;final VoidCallback? onTap;const _MapLevel({required this.unit,required this.progress,required this.unlocked,required this.previousCompleted,required this.highlight,required this.onTap});@override Widget build(BuildContext context){final isRight=unit.order.isEven;final locked=!unlocked;final current=unlocked&&!progress.completed;final world=_worldFor(unit.order);final nodeColor=locked?GameTheme.inkSoft:progress.completed?GameTheme.success:world.color;return SizedBox(height:154,child:Stack(clipBehavior:Clip.none,children:[Positioned.fill(child:CustomPaint(painter:_PathPainter(fromRight:unit.order>1&&!isRight,toRight:isRight,active:previousCompleted||progress.completed,color:world.color))),Align(alignment:Alignment(isRight ? .76 : -.76,0),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(30),child:TweenAnimationBuilder<double>(tween:Tween(begin:highlight ? .82 : 1,end:1),duration:const Duration(milliseconds:650),curve:Curves.elasticOut,builder:(context,scale,child)=>Transform.scale(scale:scale,child:child),child:_LandmarkStation(unit:unit,world:world,progress:progress,locked:locked,current:current,highlight:highlight,nodeColor:nodeColor)))),if(current||highlight)Positioned.fill(child:IgnorePointer(child:Align(alignment:Alignment(isRight ? .40 : -.40,-.72),child:ArqamiCompanion(mood: highlight ? 'celebrate' : 'happy', size: 62)))),if(highlight)const Positioned.fill(child:IgnorePointer(child:_UnlockBurst())),if(_isStageStart(unit.order))Positioned(top:0,left:isRight?null:8,right:isRight?8:null,child:_StageChip(label:world.name))]));}}
class _LandmarkStation extends StatelessWidget{final UnitModel unit;final _WorldInfo world;final UnitProgress progress;final bool locked,current,highlight;final Color nodeColor;const _LandmarkStation({required this.unit,required this.world,required this.progress,required this.locked,required this.current,required this.highlight,required this.nodeColor});@override Widget build(BuildContext context){final alpha=locked ? .78 : .96;final glow=current ? .22 : .10;return SizedBox(width:math.min(MediaQuery.sizeOf(context).width*.76,330),child:Column(mainAxisSize:MainAxisSize.min,children:[Container(padding:const EdgeInsets.fromLTRB(10,9,14,9),decoration:BoxDecoration(color:GameTheme.paper.withValues(alpha:alpha),borderRadius:BorderRadius.circular(28),border:Border.all(color:highlight||current?GameTheme.sunshine:world.color.withValues(alpha:.38),width:highlight?3:current?2.5:1.5),boxShadow:[BoxShadow(color:world.color.withValues(alpha:glow),blurRadius:current?18:9,offset:const Offset(0,5)),if(highlight)BoxShadow(color:GameTheme.sunshine.withValues(alpha:.28),blurRadius:24,spreadRadius:3)]),child:Row(children:[_LandmarkIcon(world:world,completed:progress.completed,locked:locked,current:current),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('المحطة ${unit.order}',style:Theme.of(context).textTheme.labelMedium?.copyWith(color:nodeColor,fontWeight:FontWeight.w900))),_StarsRow(stars:progress.stars)]),const SizedBox(height:2),Text(unit.titleAr,maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(context).textTheme.titleSmall?.copyWith(fontWeight:FontWeight.w900,color:locked?GameTheme.inkSoft:GameTheme.ink)),const SizedBox(height:3),Text(locked?'البوابة مغلقة':progress.completed?'تم اجتياز المحطة ✓':'ادخل المحطة والعب',style:Theme.of(context).textTheme.labelSmall?.copyWith(color:locked?GameTheme.inkSoft:world.color,fontWeight:FontWeight.w800))]))])),const SizedBox(height:3),_LandmarkBase(world:world,locked:locked,current:current)]));}}
class _LandmarkIcon extends StatelessWidget{final _WorldInfo world;final bool completed,locked,current;const _LandmarkIcon({required this.world,required this.completed,required this.locked,required this.current});@override Widget build(BuildContext context){final icon=locked?Icons.lock_rounded:completed?Icons.check_rounded:world.icon;final a1=locked ? .45 : 1.0;final a2=locked ? .35 : 1.0;final a3=current ? .28 : .14;return AnimatedContainer(duration:GameTheme.popMotion,width:current?64:58,height:current?64:58,decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[world.color.withValues(alpha:a1),world.accent.withValues(alpha:a2)]),borderRadius:BorderRadius.circular(current?22:19),border:Border.all(color:current?GameTheme.sunshine:Colors.white.withValues(alpha:.8),width:current?3:2),boxShadow:[BoxShadow(color:world.color.withValues(alpha:a3),blurRadius:current?16:8,offset:const Offset(0,4))]),child:Icon(icon,color:Colors.white,size:current?32:28));}}
class _LandmarkBase extends StatelessWidget{final _WorldInfo world;final bool locked,current;const _LandmarkBase({required this.world,required this.locked,required this.current});@override Widget build(BuildContext context){final alpha=locked ? .20 : .50;return AnimatedContainer(duration:GameTheme.popMotion,width:84,height:13,decoration:BoxDecoration(color:world.color.withValues(alpha:alpha),borderRadius:BorderRadius.circular(20),boxShadow:current?[BoxShadow(color:GameTheme.sunshine.withValues(alpha:.24),blurRadius:12)]:null),child:Center(child:Container(width:46,height:4,decoration:BoxDecoration(color:Colors.white.withValues(alpha:.65),borderRadius:BorderRadius.circular(4)))));}}
class _StageRewardNode extends StatelessWidget{final StageRewardDefinition reward;final StageRewardStatus status;final bool celebration;final VoidCallback onTap;const _StageRewardNode({required this.reward,required this.status,required this.celebration,required this.onTap});@override Widget build(BuildContext context){final available=status==StageRewardStatus.available;final claimed=status==StageRewardStatus.claimed;final color=claimed?GameTheme.success:available?GameTheme.sunshine:GameTheme.inkSoft;final scale=celebration ? .72 : available ? .92 : 1.0;final borderAlpha=claimed||available?1.0:.35;final borderWidth=claimed||available?2.5:1.5;return SizedBox(height:118,child:Center(child:GestureDetector(onTap:onTap,child:TweenAnimationBuilder<double>(tween:Tween(begin:scale,end:1),duration:const Duration(milliseconds:700),curve:Curves.elasticOut,builder:(context,value,child)=>Transform.scale(scale:value,child:child),child:Container(width:math.min(MediaQuery.sizeOf(context).width*.80,340),padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:GameTheme.paper.withValues(alpha:.96),borderRadius:BorderRadius.circular(28),border:Border.all(color:color.withValues(alpha:borderAlpha),width:borderWidth),boxShadow:[if(available)BoxShadow(color:GameTheme.sunshine.withValues(alpha:.28),blurRadius:18,spreadRadius:2)]),child:Row(children:[Container(width:62,height:62,padding:const EdgeInsets.all(12),decoration:BoxDecoration(shape:BoxShape.circle,color:color.withValues(alpha:.9)),child:Image.asset(claimed?'assets/game/rewards/checkmark.png':available?'assets/game/rewards/trophy.png':'assets/game/rewards/lock.png',color:Colors.white)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('بوابة مكافأة العالم ${reward.stage}',style:Theme.of(context).textTheme.labelMedium?.copyWith(fontWeight:FontWeight.w900,color:available?GameTheme.mango:null)),const SizedBox(height:2),Text(reward.titleAr,style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:2),Text(claimed?'تم فتح البوابة · الإنجاز محفوظ':available?'اضغط لفتح البوابة ✨':'أكمل العالم لفتحها')]))]))))));}}
class _RewardCelebration extends StatelessWidget{final StageRewardDefinition reward;const _RewardCelebration({required this.reward});@override Widget build(BuildContext context)=>Dialog(child:Stack(alignment:Alignment.center,children:[const Positioned.fill(child:GameParticleBurst(active:true,seed:91,count:36)),Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,children:[const ArqamiCompanion(mood:'celebrate',size:92),const SizedBox(height:4),const Text('أحسنت! 🎉',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text(reward.titleAr,textAlign:TextAlign.center,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('فتحت بوابة العالم التالية وحصلت على مكافأة المرحلة.',textAlign:TextAlign.center),const SizedBox(height:12),Row(mainAxisAlignment:MainAxisAlignment.center,children:List.generate(3,(i)=>Padding(padding:const EdgeInsets.all(3),child:Image.asset('assets/game/rewards/star.png',width:30,height:30,color:GameTheme.sunshine)))),const SizedBox(height:12),FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('متابعة الرحلة'))]))]));}
class _UnlockBurst extends StatelessWidget{const _UnlockBurst();@override Widget build(BuildContext context)=>TweenAnimationBuilder<double>(tween:Tween(begin:.15,end:1),duration:const Duration(milliseconds:900),curve:Curves.easeOut,builder:(context,value,child)=>Stack(alignment:Alignment.center,children:[Transform.scale(scale:.45+value*.9,child:Opacity(opacity:(1-value)*.75,child:Container(width:88,height:88,decoration:BoxDecoration(shape:BoxShape.circle,border:Border.all(color:GameTheme.sunshine,width:3))))),Transform.rotate(angle:value*math.pi*.12,child:Opacity(opacity:1-value,child:const Icon(Icons.auto_awesome_rounded,size:48,color:GameTheme.sunshine))) ]));}
class _StageChip extends StatelessWidget{final String label;const _StageChip({required this.label});@override Widget build(BuildContext context)=>DecoratedBox(decoration:BoxDecoration(gradient:const LinearGradient(colors:[GameTheme.ocean,GameTheme.violet]),borderRadius:BorderRadius.circular(16)),child:Padding(padding:const EdgeInsets.symmetric(horizontal:11,vertical:6),child:Text(label,style:const TextStyle(color:Colors.white,fontSize:11,fontWeight:FontWeight.w900))));}
class _StarsRow extends StatelessWidget{final int stars;const _StarsRow({required this.stars});@override Widget build(BuildContext context)=>Row(mainAxisSize:MainAxisSize.min,children:List.generate(3,(index)=>Padding(padding:const EdgeInsetsDirectional.only(end:2),child:Opacity(opacity:index<stars?1:.22,child:Image.asset('assets/game/rewards/star.png',width:16,height:16,color:GameTheme.sunshine)))));}
class _PathPainter extends CustomPainter{final bool fromRight,toRight,active;final Color color;const _PathPainter({required this.fromRight,required this.toRight,required this.active,required this.color});@override void paint(Canvas canvas,Size size){final startX=fromRight?size.width*.76:size.width*.24;final endX=toRight?size.width*.76:size.width*.24;final paint=Paint();paint.color=active?color.withValues(alpha:.38):GameTheme.inkSoft.withValues(alpha:.20);paint.strokeWidth=6;paint.style=PaintingStyle.stroke;paint.strokeCap=StrokeCap.round;final path=Path()..moveTo(startX,0)..cubicTo(startX,size.height*.30,endX,size.height*.70,endX,size.height);canvas.drawPath(path,paint);final dot=Paint()..color=color.withValues(alpha:active ? .35 : .12);for(var i=1;i<5;i++){canvas.drawCircle(Offset(startX+(endX-startX)*i/5,size.height*i/5),2.5,dot);}}@override bool shouldRepaint(covariant _PathPainter oldDelegate)=>oldDelegate.fromRight!=fromRight||oldDelegate.toRight!=toRight||oldDelegate.active!=active||oldDelegate.color!=color;}
class _WorldInfo{final String name;final Color color,accent;final IconData icon;const _WorldInfo(this.name,this.color,this.accent,this.icon);}
